apiVersion: v2
name: picoclaw
description: A Helm chart for picoclaw gateway
version: 0.1.22
icon: https://mattn.github.io/picoclaw-charts/icon.png
home: https://github.com/sipeed/picoclaw
sources:
  - https://github.com/sipeed/picoclaw
  - https://github.com/mattn/picoclaw-charts
